from setuptools import setup, find_packages

setup(
    name="UniversalCVI",
    version="1.0.0",
    author="Boudsalakham Saynorlath",
    author_email="saynoboud@gmail.com",
    description="Hard and Soft Cluster Validity Indices",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/sayboud/UniversalCVI",
    packages=find_packages(),
    install_requires=open("requirements.txt").read().splitlines(),
    python_requires=">=3.8",
   classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
],
keywords=[
    "clustering",
    "cluster validity index",
    "CVI",
    "fuzzy c-means",
    "FCM",
    "expectation maximization",
    "EM",
    "Gaussian mixture model",
    "GMM",
    "kmeans",
    "hierarchical clustering",
    "XB",
    "Xie-Beni",
    "KWON",
    "KWON2",
    "TANG",
    "HF",
    "WL",
    "PBM",
    "KPBM",
    "CCV",
    "CCVP",
    "CCVS",
    "GC",
    "WP",
    "NC",
    "NCI",
    "CH",
    "Calinski-Harabasz",
    "DB",
    "Davies-Bouldin",
    "DI",
    "Dunn",
    "CSL",
    "PB",
    "SF",
    "SH",
    "silhouette",
    "STR",
    "unsupervised learning",
    "machine learning",
]
)